{
 "title": "Demo API dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "method",
    "query": {
     "query": "label_values(http_request_method)"
    }
   },
   { "name": "route", "query": { "query": "label_values(http_route)" } },
   {
    "name": "status",
    "query": {
     "query": "label_values(http_response_status_code)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests Over ${interval}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(http_server_request_duration_seconds_count{http_request_method=~\"$method\", http_route=~\"$route\", http_response_status_code=~\"$status\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ASP .NET Core Routing Match Attempts Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aspnetcore_routing_match_attempts_total{http_route=~\"$route\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Request Duration Over ${interval}",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(http_server_request_duration_seconds_sum{http_request_method=~\"$method\", http_route=~\"$route\", http_response_status_code=~\"$status\"}[$interval]) / increase(http_server_request_duration_seconds_count{http_request_method=~\"$method\", http_route=~\"$route\", http_response_status_code=~\"$status\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of Request Methods",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(http_request_method) (max_over_time(http_server_request_duration_seconds_count{http_route=~\"$route\", http_response_status_code=~\"$status\", http_request_method=~\"$status|$method\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of Request Status Codes",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(http_response_status_code) (max_over_time(http_server_request_duration_seconds_count{http_route=~\"$route\", http_request_method=~\"$method\", http_response_status_code=~\"$status\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}