{
 "title": "Demo API dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ASP .NET Core Routing Match Attempts Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aspnetcore_routing_match_attempts_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ASP .NET Core Routing Successful Matches Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "aspnetcore_routing_match_attempts_total{aspnetcore_routing_match_status=\"success\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration Count",
   "type": "histogram",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Server Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "expr": "http_server_active_requests", "legendFormat": "__auto" }
   ]
  }
 ]
}